using Core.Entities;
using System;

namespace Entities.Concrete
{
    /// <summary>
    /// Referral codes generated by users to invite new users.
    /// Format: ZIRA-ABC123 (configurable prefix + 6 alphanumeric)
    /// </summary>
    public class ReferralCode : IEntity
    {
        public int Id { get; set; }

        /// <summary>
        /// User who generated this referral code (referrer)
        /// </summary>
        public int UserId { get; set; }

        /// <summary>
        /// Unique referral code (e.g., ZIRA-ABC123)
        /// Format: {Prefix}-{6 characters} without confusing chars (0,O,1,I,etc.)
        /// </summary>
        public string Code { get; set; }

        /// <summary>
        /// Whether this code is active and can be used
        /// </summary>
        public bool IsActive { get; set; }

        /// <summary>
        /// When this code was created
        /// </summary>
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// When this code expires (CreatedAt + configured expiry days, default 30 days)
        /// </summary>
        public DateTime ExpiresAt { get; set; }

        /// <summary>
        /// Code status: 0=Active, 1=Expired, 2=Disabled
        /// </summary>
        public int Status { get; set; }
    }

    /// <summary>
    /// Referral code status enumeration
    /// </summary>
    public enum ReferralCodeStatus
    {
        Active = 0,
        Expired = 1,
        Disabled = 2
    }
}
